package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Friday, May 18, 2018 10:52:58 PM SGT
*/

public interface HelloOperations 
{
  String hellomessage ();
  void hellomessage (String newHellomessage);
} // interface HelloOperations
